import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import fs from 'fs';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import requestRoutes from './routes/requestRoutes.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
if (!fs.existsSync('./uploads')) fs.mkdirSync('./uploads');
connectDB();
app.use('/uploads', express.static('uploads'));
app.use('/api/auth', authRoutes);
app.use('/api/requests', requestRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
